# Config file for GitHub dependabot

version: 2
updates:

  - package-ecosystem: "pip"

    # directory in which *.txt files are scanned
    directory: "/"

    schedule:
      interval: "weekly"
      day: "saturday"

    # overwrites the default labels "dependencies" and "python"
    labels:
      - "dependabot"
      - "backport"
