# Safety policy file
# For documentation, see https://docs.pyup.io/docs/safety-20-policy-file

# Configuration for the 'safety check' command
security:

    # Ignore certain severities.
    # A number between 0 and 10, with the following significant values:
    # - 9: ignore all vulnerabilities except CRITICAL severity
    # - 7: ignore all vulnerabilities except CRITICAL & HIGH severity
    # - 4: ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity
    ignore-cvss-severity-below: 0

    # Ignore unknown severities.
    # Should be set to False.
    ignore-cvss-unknown-severity: False

    # List of specific vulnerabilities to ignore.
    # {id}:                 # vulnerability ID
    #     reason: {text}    # optional: Reason for ignoring it. Will be reported in the Safety reports
    #     expires: {date}   # optional: Date when this ignore will expire
    ignore-vulnerabilities:
        37504:
            reason: Fixed Twine version requires Python>=3.6 and is used there
        38330:
            reason: Fixed Sphinx version requires Python>=3.5 and is used there
        39611:
            reason: PyYAML full_load method or FullLoader is not used
        39621:
            reason: Fixed Pylint version requires Python>=3.6 and is used there
        40291:
            reason: Fixed Pip version requires Python>=3.6 and is used there
        40380:
            reason: Fixed Notebook version requires Python>=3.6 and is used there
        40381:
            reason: Fixed Notebook version requires Python>=3.6 and is used there
        40383:
            reason: Fixed Notebook version requires Python>=3.6 and is used there
        40384:
            reason: Fixed Notebook version requires Python>=3.6 and is used there
        40385:
            reason: Fixed Notebook version requires Python>=3.6 and is used there
        40386:
            reason: Fixed Notebook version requires Python>=3.6 and is used there
        42253:
            reason: Fixed Notebook version requires Python>=3.6 and is used there
        42254:
            reason: Fixed Notebook version requires Python>=3.6 and is used there
        42559:
            reason: Fixed Pip version requires Python>=3.6 and is used there; Pip is not shipped with this package
        43975:
            reason: Fixed Urllib3 versions are excluded by requests
        44634:
            reason: Fixed Ipython version requires Python>=3.3 and is used there
        45185:
            reason: Fixed Pylint version requires Python>=3.6.2 and is used there
        45775:
            reason: Fixed Sphinx version requires Python>=3.5 and is used there
        50463:
            reason: Fixed Ipywidgets version requires Python>=3.7 and is used there
        50664:
            reason: Fixed Ipywidgets version requires Python>=3.7 and is used there
        50792:
            reason: Fixed Nbconvert version requires Python>=3.7 and is used there
        50885:
            reason: Fixed Pygments version requires Python>=3.5 and is used there
        50886:
            reason: Fixed Pygments version requires Python>=3.5 and is used there
        51457:
            reason: Py package is no longer being fixed (latest version 1.11.0)
        51499:
            reason: Fixed Wheel version requires Python>=3.7 and is used there; Risk is on Pypi side
        52322:
            reason: Fixed GitPython version requires Python>=3.7 and is used there
        52365:
            reason: Fixed Certifi version requires Python>=3.6 and is used there
        52495:
            reason: Fixed Setuptools version requires Python>=3.7 and is used there; Risk is on Pypi side
        52518:
            reason: Fixed GitPython version requires Python>=3.7 and is used there
        53269:
            reason: Fixed Ipython version 8.1.0 cannot be used without major work on dependencies; Risk is minimal since this is used only in development
        54687:
            reason: Fixed pywin32 version 301 requires Python>=3.5 and is used there
        54717:
            reason: Fixed jupyter-core version 4.11.2 requires Python>=3.7 and is used there
        54713:
            reason: Fixed notebook version 6.4.10 requires Python>=3.6 and is used there
        54684:
            reason: Fixed notebook version 6.4.12 requires Python>=3.7 and is used there
        54678:
            reason: Fixed notebook version 5.7.8 only works on Python>=3.6 and is used there
        54682:
            reason: Fixed notebook version 5.5.0 only works on Python>=3.6 and is used there
        54689:
            reason: Fixed notebook version 5.7.11 only works on Python>=3.6 and is used there
        58755:
            reason: Fixed requests version 2.31.0 requires Python>=3.7 and is used there
        58910:
            reason: Fixed pygments version 2.15.0 requires Python>=3.7 and is used there

    # Continue with exit code 0 when vulnerabilities are found.
    continue-on-vulnerability-error: False
