# This GitHub workflow will publish the package to Pypi.
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: publish

on:
  push:  # When pushing a tag
    tags:
    - "*"

jobs:
  build-n-publish:
    name: Build and publish to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - name: Display github.ref
      run: |
        echo ${{ github.ref }}
    # - name: Checkout repo
    #   uses: actions/checkout@v2
    #   with:
    #     fetch-depth: 0
    # - name: Set up Python 3.10
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.10"
    # - name: Development setup
    #   run: |
    #     make develop
    # - name: Run build
    #   run: |
    #     make build
    #     ls -l dist
    # - name: Publish to TestPyPI
    #   if: startsWith(github.ref, 'refs/tags')
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #     repository_url: https://test.pypi.org/legacy/
    # - name: Publish distribution to PyPI
    #   if: startsWith(github.ref, 'refs/tags')
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}
    # - name: Display github.ref
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     BRANCH: stable_${{ github.ref }}
    #   run: |
    #     git checkout -b ${{ BRANCH }}
    #     git push --set-upstream origin ${{ BRANCH }}
